spring.application.name=Workflow_management
spring.datasource.url=jdbc:postgresql://localhost:5432/workflow_db
spring.datasource.username=postgres
spring.datasource.password=Abhay@128
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true
server.port=9091
jwt.secret=7q8d8c8vJJjmY3UT2BQ8NYDBJDFifvbdhiudfhre72behber4hbq=
jwt.expiration=1200000
